### ISSUE TITLE
Please remove binaries

### ISSUE THREAD

**Issue by pcav** [WinCan/QGISPlugin#4]
Only source code is allowed here.
Thanks.

**Comment by 3nids** [comment]
It is currently not accepted to ship binaries in the plugin archive, and you should rather offer a way to the user to download it and use it afterwards.
We have another plugin to import Wincan (old format) data into the Swiss waste-water offical data format: https://github.com/QGEP/wincan2qgep
We will first migrate this to QGIS 3 and in a second step allow the new format.
I would be happy to collaborate and we could implement the download interface.
Best regards
